# Generated by Django 4.2.7 on 2023-12-08 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="audiofile",
            old_name="uploaded_at",
            new_name="upload_date",
        ),
        migrations.RemoveField(
            model_name="audiofile",
            name="file",
        ),
        migrations.AddField(
            model_name="audiofile",
            name="drive_file_id",
            field=models.CharField(default="NOT_SET", max_length=255),
        ),
        migrations.AddField(
            model_name="audiofile",
            name="file_name",
            field=models.CharField(default="unnamed_file", max_length=255),
        ),
        migrations.CreateModel(
            name="EvaluationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result_data", models.JSONField()),
                ("evaluated_on", models.DateTimeField(auto_now_add=True)),
                (
                    "audio_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.audiofile"
                    ),
                ),
                (
                    "scorecard",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.scorecard",
                    ),
                ),
            ],
        ),
    ]
