# Generated by Django 5.0 on 2024-02-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiofile",
            name="duration_seconds",
            field=models.FloatField(default=0.0),
        ),
    ]
