# Generated by Django 4.2.7 on 2023-12-08 09:21

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_rename_uploaded_at_audiofile_upload_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audiofile",
            name="drive_file_id",
        ),
        migrations.AddField(
            model_name="audiofile",
            name="audio",
            field=models.FileField(null=True, upload_to=api.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name="audiofile",
            name="file_name",
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name="EvaluationResult",
        ),
    ]
