# Generated by Django 5.0 on 2024-02-15 11:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_audiofile_duration_seconds"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transcript",
            name="text",
        ),
    ]
