# Generated by Django 5.0 on 2023-12-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_evaluation"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiofile",
            name="transcription",
            field=models.TextField(blank=True, null=True),
        ),
    ]
