# Generated by Django 5.0 on 2024-01-09 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_evaluation_individual_reports"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transcript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True)),
                (
                    "audio_file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcript",
                        to="api.audiofile",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="audiofile",
            name="transcription",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.transcript",
            ),
        ),
        migrations.CreateModel(
            name="Utterance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("speaker_label", models.CharField(max_length=2)),
                ("start_time", models.FloatField()),
                ("end_time", models.FloatField()),
                ("confidence", models.FloatField()),
                ("text", models.TextField()),
                (
                    "transcript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utterances",
                        to="api.transcript",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("confidence", models.FloatField()),
                ("start_time", models.FloatField()),
                ("end_time", models.FloatField()),
                (
                    "utterance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words",
                        to="api.utterance",
                    ),
                ),
            ],
        ),
    ]
