# Generated by Django 5.0 on 2024-01-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_transcript_formatted_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utterance",
            name="low_confidence_words",
            field=models.JSONField(default=dict),
        ),
    ]
