# Generated by Django 5.0 on 2024-01-10 09:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_alter_utterance_low_confidence_words"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transcript",
            name="formatted_text",
        ),
    ]
