# Generated by Django 5.0 on 2024-01-30 08:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_category_scorecard_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
