# Generated by Django 5.0 on 2024-02-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_remove_evaluation_audio_files_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationjob",
            name="audio_files",
            field=models.ManyToManyField(to="api.audiofile"),
        ),
    ]
